# Array values

# Shortened names with the first letter capitalized - String
# ############################################################
ARRAY.WEEKDAY.SHORT.0 = Sun
ARRAY.WEEKDAY.SHORT.1 = Mon
ARRAY.WEEKDAY.SHORT.2 = Tue
ARRAY.WEEKDAY.SHORT.3 = Wed
ARRAY.WEEKDAY.SHORT.4 = Thu
ARRAY.WEEKDAY.SHORT.5 = Fri
ARRAY.WEEKDAY.SHORT.6 = Sat
# ############################################################

# Shortened names all letters capitalized - String
# ############################################################
ARRAY.WEEKDAY.SHORTCAP.0 = SUN
ARRAY.WEEKDAY.SHORTCAP.1 = MON
ARRAY.WEEKDAY.SHORTCAP.2 = TUE
ARRAY.WEEKDAY.SHORTCAP.3 = WED
ARRAY.WEEKDAY.SHORTCAP.4 = THU
ARRAY.WEEKDAY.SHORTCAP.5 = FRI
ARRAY.WEEKDAY.SHORTCAP.6 = SAT
# ############################################################

# Full length names, first letters capitalized - String
# ############################################################
ARRAY.WEEKDAY.LONG.0 = Sunday
ARRAY.WEEKDAY.LONG.1 = Monday
ARRAY.WEEKDAY.LONG.2 = Tuesday
ARRAY.WEEKDAY.LONG.3 = Wednesday
ARRAY.WEEKDAY.LONG.4 = Thursday
ARRAY.WEEKDAY.LONG.5 = Friday
ARRAY.WEEKDAY.LONG.6 = Saturday
# ############################################################

# Full length names all letters capitalized - String
# ############################################################
ARRAY.WEEKDAY.LONGCAP.0 = SUNDAY
ARRAY.WEEKDAY.LONGCAP.1 = MONDAY
ARRAY.WEEKDAY.LONGCAP.2 = TUESDAY
ARRAY.WEEKDAY.LONGCAP.3 = WEDNESDAY
ARRAY.WEEKDAY.LONGCAP.4 = THURSDAY
ARRAY.WEEKDAY.LONGCAP.5 = FRIDAY
ARRAY.WEEKDAY.LONGCAP.6 = SATURDAY
# ############################################################

# AM/PM interval - String
# ############################################################
ARRAY.AMPM.0 = AM
ARRAY.AMPM.1 = PM
# ############################################################

# Time Intervals - int
# ############################################################
ARRAY.TIME.0 = 0
ARRAY.TIME.1 = 23
ARRAY.TIME.2 = 0
ARRAY.TIME.3 = 59
# ############################################################

# ID Intervals  - int
# ############################################################
ARRAY.ID.0 = 0
ARRAY.ID.1 = 9999999
# ############################################################