# Unique values

# various int values - parse to int
# ############################################################
# WeekDay Length
UNIQUE.INT.0 = 7
# ############################################################

# UI Spacing - parse to double
# ############################################################
UNIQUE.DOUBLE.SPACING.0 = 10
UNIQUE.DOUBLE.SPACING.1 = 15
UNIQUE.DOUBLE.SPACING.2 = 20
UNIQUE.DOUBLE.SPACING.3 = 25
UNIQUE.DOUBLE.SPACING.4 = 30
# ############################################################

# UI Padding - parse to double
# ############################################################
UNIQUE.DOUBLE.PADDING.0 = 5
UNIQUE.DOUBLE.PADDING.1 = 10
UNIQUE.DOUBLE.PADDING.2 = 15
UNIQUE.DOUBLE.PADDING.3 = 20
UNIQUE.DOUBLE.PADDING.4 = 25
# ############################################################

# UI Width - parse to double
# ############################################################
UNIQUE.DOUBLE.WIDTH.0 = 50
UNIQUE.DOUBLE.WIDTH.1 = 100
UNIQUE.DOUBLE.WIDTH.2 = 150
UNIQUE.DOUBLE.WIDTH.3 = 200
UNIQUE.DOUBLE.WIDTH.4 = 250
UNIQUE.DOUBLE.WIDTH.5 = 300
UNIQUE.DOUBLE.WIDTH.6 = 400
# ############################################################

# UI Height - parse to double
# ############################################################
UNIQUE.DOUBLE.HEIGHT.0 = 20
UNIQUE.DOUBLE.HEIGHT.1 = 25
UNIQUE.DOUBLE.HEIGHT.2 = 30
UNIQUE.DOUBLE.HEIGHT.3 = 35
UNIQUE.DOUBLE.HEIGHT.4 = 40
UNIQUE.DOUBLE.HEIGHT.5 = 45
UNIQUE.DOUBLE.HEIGHT.6 = 50
UNIQUE.DOUBLE.HEIGHT.7 = 100
UNIQUE.DOUBLE.HEIGHT.8 = 200
# ############################################################

# UI ANCHOR Position - parse to double
# ############################################################
UNIQUE.DOUBLE.ANCHOR.0 = 5
UNIQUE.DOUBLE.ANCHOR.1 = 10
UNIQUE.DOUBLE.ANCHOR.2 = 15
UNIQUE.DOUBLE.ANCHOR.3 = 20
UNIQUE.DOUBLE.ANCHOR.4 = 25
# ############################################################