# Title
TITLE.0 = Meeting Scheduler Instructions

DESCRIPTION.0 = - A how to guide for using this application -

PAGEINFO.0 =DataCard________By accessing the data card page you will be able to add, update and remove user preferences for different employees.
PAGEINFO.1 =Scheduling______By accessing the scheudling seciton you can create schedules based on specified user reference.
PAGEINFO.2 =Instructions_____How to guide for the programs use.

EXTRATEXT.0 = This application is developed for handling repeating weekly schedules and scheduling meetings based off of that. When Inputing employee preferences in the
EXTRATEXT.1 = datacard page, the user should be inputing the weekly schedules for that employee, i.e if someone is scheduled to work monday through friday from 9am to 5pm,
EXTRATEXT.2 = then their preference interval should lie sometime within that timeframe, while simultaneously being a reoccuring preference. Put simply, if a preference
EXTRATEXT.3 = occurs every week at the same time, then it should be input. If a preference only occurs once or not very often it should not be input. This program is used
EXTRATEXT.4 = to quickly determine viable schedules for a vast number of people with various working hours, quickly returning intervals so the user does not have to 
EXTRATEXT.5 = continously cross reference and check hours when a potential timeframe is not viable.