# Unique values

# various int values - parse to int
# ############################################################
# WeekDay Length
UNIQUE.INT.1 = 7;
# ############################################################

# UI Spacing - parse to double
# ############################################################
UNIQUE.DOUBLE.SPACING.1 = 10
UNIQUE.DOUBLE.SPACING.2 = 15
UNIQUE.DOUBLE.SPACING.3 = 20
UNIQUE.DOUBLE.SPACING.4 = 25
UNIQUE.DOUBLE.SPACING.5 = 30
# ############################################################

# UI Padding - parse to double
# ############################################################
UNIQUE.DOUBLE.PADDING.1 = 5
UNIQUE.DOUBLE.PADDING.2 = 10
UNIQUE.DOUBLE.PADDING.3 = 15
UNIQUE.DOUBLE.PADDING.4 = 20
UNIQUE.DOUBLE.PADDING.5 = 25
# ############################################################

# UI Width - parse to double
# ############################################################
UNIQUE.DOUBLE.WIDTH.1 = 50
UNIQUE.DOUBLE.WIDTH.2 = 100
UNIQUE.DOUBLE.WIDTH.3 = 150
UNIQUE.DOUBLE.WIDTH.4 = 200
UNIQUE.DOUBLE.WIDTH.5 = 250
UNIQUE.DOUBLE.WIDTH.6 = 300
UNIQUE.DOUBLE.WIDTH.7 = 400
# ############################################################

# UI Height - parse to double
# ############################################################
UNIQUE.DOUBLE.HEIGHT.1 = 20
UNIQUE.DOUBLE.HEIGHT.2 = 25
UNIQUE.DOUBLE.HEIGHT.3 = 30
UNIQUE.DOUBLE.HEIGHT.4 = 35
UNIQUE.DOUBLE.HEIGHT.5 = 40
UNIQUE.DOUBLE.HEIGHT.6 = 45
UNIQUE.DOUBLE.HEIGHT.7 = 50
UNIQUE.DOUBLE.HEIGHT.8 = 100
UNIQUE.DOUBLE.HEIGHT.9 = 200
# ############################################################

# UI ANCHOR Position - parse to double
# ############################################################
UNIQUE.DOUBLE.ANCHOR.1 = 5
UNIQUE.DOUBLE.ANCHOR.2 = 10
UNIQUE.DOUBLE.ANCHOR.3 = 15
UNIQUE.DOUBLE.ANCHOR.4 = 20
UNIQUE.DOUBLE.ANCHOR.5 = 25
# ############################################################