# Array values

# Shortened names with the first letter capitalized
# ############################################################
ARRAY.WEEKDAY.SHORT.1 = Sun
ARRAY.WEEKDAY.SHORT.2 = Mon
ARRAY.WEEKDAY.SHORT.3 = Tue
ARRAY.WEEKDAY.SHORT.4 = Wed
ARRAY.WEEKDAY.SHORT.5 = Thu
ARRAY.WEEKDAY.SHORT.6 = Fri
ARRAY.WEEKDAY.SHORT.7 = Sat
# ############################################################

# Shortened names all letters capitalized
# ############################################################
ARRAY.WEEKDAY.SHORTCAP.1 = SUN
ARRAY.WEEKDAY.SHORTCAP.2 = MON
ARRAY.WEEKDAY.SHORTCAP.3 = TUE
ARRAY.WEEKDAY.SHORTCAP.4 = WED
ARRAY.WEEKDAY.SHORTCAP.5 = THU
ARRAY.WEEKDAY.SHORTCAP.6 = FRI
ARRAY.WEEKDAY.SHORTCAP.7 = SAT
# ############################################################

# Full length names, first letters capitalized
# ############################################################
ARRAY.WEEKDAY.LONG.1 = Sunday
ARRAY.WEEKDAY.LONG.2 = Monday
ARRAY.WEEKDAY.LONG.3 = Tuesday
ARRAY.WEEKDAY.LONG.4 = Wednesday
ARRAY.WEEKDAY.LONG.5 = Thursday
ARRAY.WEEKDAY.LONG.6 = Friday
ARRAY.WEEKDAY.LONG.7 = Saturday
# ############################################################

# Full length names all letters capitalized
# ############################################################
ARRAY.WEEKDAY.LONGCAP.1 = SUNDAY
ARRAY.WEEKDAY.LONGCAP.2 = MONDAY
ARRAY.WEEKDAY.LONGCAP.3 = TUESDAY
ARRAY.WEEKDAY.LONGCAP.4 = WEDNESDAY
ARRAY.WEEKDAY.LONGCAP.5 = THURSDAY
ARRAY.WEEKDAY.LONGCAP.6 = FRIDAY
ARRAY.WEEKDAY.LONGCAP.7 = SATURDAY
# ############################################################

# AM/PM interval
# ############################################################
ARRAY.AMPM.1 = AM
ARRAY.AMPM.2 = PM
# ############################################################

# Time Intervals
# ############################################################
ARRAY.TIME.HOUR.1   = 0
ARRAY.TIME.HOUR.2   = 23
ARRAY.TIME.MIN.1    = 0
ARRAY.TIME.MIN.2    = 59
# ############################################################

# ID Intervals
# ############################################################
ARRAY.INTERVAL.ID.1 = 0
ARRAY.INTERVAL.ID.2 = 9999999
# ############################################################