/*
 * This source file was generated by the Gradle 'init' task
 */
package meeting_scheduler;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.core.exc.StreamReadException;
import com.fasterxml.jackson.core.exc.StreamWriteException;
import com.fasterxml.jackson.databind.DatabindException;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.util.LinkedList;

import meeting_scheduler.BusinessLogiclayer.PROG_BLL_InfoFileWrite;
import meeting_scheduler.DataAccessLayer.PROG_DAL_A_InfoInput;
import meeting_scheduler.DataAccessLayer.PROG_DAL_A_Schedule;
import meeting_scheduler.DataAccessLayer.PROG_DAL_A_TimeInput;
import meeting_scheduler.DataAccessLayer.PROG_DAL_B_JSONManager;

class AppTest {

    /**
     * Format for method naming
     * 
     * TEST_(TypeOfTest)_(basicTestDescription)
     * 
     * INFO     - Idicates test directly ties to user data variables
     * FILE     - Indicates test focuses on file management/manipulation
     * BLL      - Tests the business logic layer operations
     * UI       - Indicates test focusing on UI functinality
     * GRAPH    - Indicates visual test for graphical elements
     */



    /**
     * Constructor
     */
    public AppTest() {


    }


    
    /**
     * INFO Test Section
     * Description: This section tests user data such as objects that hold user card info
     */
    @Test void TEST_TimeInput() {
        
        PROG_DAL_A_TimeInput test_TimeInterval = new PROG_DAL_A_TimeInput("Mon", 03, 50, 14, 07);

        // Object not null
        assertNotNull(test_TimeInterval);

        // day is correct
        assertEquals(test_TimeInterval.WeekDay, "Mon");

        // Beginning hour and minute correct
        assertEquals(test_TimeInterval.PreferedHourBEGIN.getHour(), 03);
        assertEquals(test_TimeInterval.PreferedHourBEGIN.getMinute(), 50);

        // Ending hour and minute correct
        assertEquals(test_TimeInterval.PreferedHourEND.getHour(), 14);
        assertEquals(test_TimeInterval.PreferedHourEND.getMinute(), 07);

        test_TimeInterval = null;
    }


    @Test void TEST_InfoInput() {

        // Test object build parameter
        String[]                            Week = new String[] {"Mon", "Wed", "Thu"};
        LinkedList<PROG_DAL_A_TimeInput>    test_timeintervals = new LinkedList<PROG_DAL_A_TimeInput>();
        PROG_DAL_A_TimeInput                test_TimeInterval = new PROG_DAL_A_TimeInput("Mon", 03, 50, 14, 07);
        
        test_timeintervals.add(test_TimeInterval);



        // Object being tested
        PROG_DAL_A_InfoInput Test_person = new PROG_DAL_A_InfoInput("John Smith", 1007, Week, test_timeintervals);

        // Object not null
        assertNotNull(Test_person);

        // name is correct
        assertEquals(Test_person.EmployeeName, "John Smith");

        // ID is correct
        assertEquals(Test_person.EmployeeID, 1007);

        // weekday is correct
        assertEquals(Test_person.TimeIntervals.get(0).WeekDay, "Mon");

        // Beginning hour and minute correct
        assertEquals(Test_person.TimeIntervals.get(0).PreferedHourBEGIN.getHour(), 03);
        assertEquals(Test_person.TimeIntervals.get(0).PreferedHourBEGIN.getMinute(), 50);

        // Ending hour and minute correct
        assertEquals(Test_person.TimeIntervals.get(0).PreferedHourEND.getHour(), 14);
        assertEquals(Test_person.TimeIntervals.get(0).PreferedHourEND.getMinute(), 07);



        // garbage collection
        test_TimeInterval   = null;
        test_timeintervals  = null;
        Test_person         = null;

    }


    @Test void TEST_Schedule() {

        PROG_DAL_A_TimeInput test_TimeInterval = new PROG_DAL_A_TimeInput("Mon", 03, 50, 14, 07);

        LinkedList<String> test_Ids = new LinkedList<>();

        test_Ids.add("1007");


        // Object being testec
        PROG_DAL_A_Schedule test_schedule = new PROG_DAL_A_Schedule("Mon", test_TimeInterval, test_Ids, true);

        assertNotNull(test_schedule);

        assertEquals(test_schedule.WeekDay, "Mon");

        // weekday is correct
        assertEquals(test_schedule.WeekDay, "Mon");

        // Beginning hour and minute correct
        assertEquals(test_schedule.Interval.PreferedHourBEGIN.getHour(), 03);
        assertEquals(test_schedule.Interval.PreferedHourBEGIN.getMinute(), 50);

        // Ending hour and minute correct
        assertEquals(test_schedule.Interval.PreferedHourEND.getHour(), 14);
        assertEquals(test_schedule.Interval.PreferedHourEND.getMinute(), 07);

    }



    /**
     * FILE Test Section
     * Description: This section tests file reading writing and organization operations
     * @throws IOException 
     * @throws DatabindException 
     * @throws StreamWriteException 
     */
    @Test void TEST_JsonManager() throws StreamWriteException, DatabindException, IOException {

        // // week days
        // String[]                            Week = new String[] {"Mon", "Wed", "Thu"};
        // // time intervals
        // LinkedList<PROG_DAL_A_TimeInput>    test_timeintervals = new LinkedList<PROG_DAL_A_TimeInput>();
        // // single time interval
        // PROG_DAL_A_TimeInput                test_TimeInterval = new PROG_DAL_A_TimeInput("Mon", 03, 50, 14, 07);
        // // add time interval to list
        // test_timeintervals.add(test_TimeInterval);

        // // person
        // PROG_DAL_A_InfoInput                Test_person = new PROG_DAL_A_InfoInput("John Smith", 1007, Week, test_timeintervals);

        // //list of people
        // LinkedList<PROG_DAL_A_InfoInput>    test_peopleList = new LinkedList<>();

        // // add person to list
        // test_peopleList.add(Test_person);


        PROG_DAL_B_JSONManager test_JsonFilemanager = new PROG_DAL_B_JSONManager();

        // test_JsonFilemanager.SetUserCards(test_peopleList);

        assertNotNull(test_JsonFilemanager);

        test_JsonFilemanager.JsonWriteTest2();

    }

    @Test void TEST_TXTInput() {

    }

    @Test void TEST_TXTOutput() {

    }


    /**
     * BLL Test Section
     * Description: This section tests the Businesslogiclayer
     * @throws IOException 
     * @throws DatabindException 
     * @throws StreamReadException 
     */
    @Test void TEST_InfoFileWrite() throws StreamReadException, DatabindException, IOException {

        // Test object build parameter
        String[]                            Week = new String[] {"Mon", "Wed", "Thu"};
        LinkedList<PROG_DAL_A_TimeInput>    test_timeintervals = new LinkedList<PROG_DAL_A_TimeInput>();
        PROG_DAL_A_TimeInput                test_TimeInterval = new PROG_DAL_A_TimeInput("Mon", 03, 50, 14, 07);
        
        test_timeintervals.add(test_TimeInterval);


        //Object being tested
        PROG_BLL_InfoFileWrite test_InfoFileWrite = new PROG_BLL_InfoFileWrite();

        // Object not null
        assertNotNull(test_InfoFileWrite);

        // adding info returns without error
        assertEquals(test_InfoFileWrite.CheckUserInfo("John Smith", 1007, Week, test_timeintervals), 0);

        // WriteUserInfo
        assertEquals(test_InfoFileWrite.WriteUserInfo(), 0);
    }

    @Test void TEST_SchedulingCalculation() {

    }


    /**
     * UI Test Section
     * Description: Tests the user interface
     */



    /**
     * Full Test section
     * Description: this ection is meant for the full testing of all major components of a certain type
     * as well as full testing of the full application.
     */
    @Test void TEST_ALL_Info() {

    }

    @Test void TEST_ALL_File() {

    }

    @Test void FULLTEST_UI() {

    }

} // TEST_ALL_FullTest


    // @Test void appHasAGreeting() {
    //     MeetingScheduler classUnderTest = new MeetingScheduler();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
