/*
 * This source file was generated by the Gradle 'init' task
 */
package meeting_scheduler;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {

    // @Test void appHasAGreeting() {
    //     MeetingScheduler classUnderTest = new MeetingScheduler();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
