# Global System Action properties
# Holds various actions that might occur during the operation of the program
# STATES:
# SYST
# USER


# Systsem Actions - Actions the program must perform such as startup functions or allocating system messages
# ############################################################
ACTION.SYST.0 = SYSTEM-TEST
ACTION.SYST.1 = SYSTEM-START
ACTION.SYST.2 = SYSTEM-END
ACTION.SYST.3 = SYSTEM-CreateGlobalValues
ACTION.SYST.4 = SYSTEM-CreateApplication
ACTION.SYST.5 = SYSTEM-CreateScenes
ACTION.SYST.6 = SYSTEM-SetGlobalValues
ACTION.SYST.7 = SYSTEM-SetApplication
ACTION.SYST.8 = SYSTEM-SetScenes
ACTION.SYST.9 = SYSTEM-GetGlobalValues
ACTION.SYST.10 = SYSTEM-FileAccess
ACTION.SYST.11 = SYSTEM-switchScene

# User Actions - Actions directly related to user input (i.e a button press)
# ############################################################
# 12
ACTION.USER.0 = USER-ButtonPress
# 13
ACTION.USER.1 = USER-AddingInfo
# 14
ACTION.USER.2 = USER-SubmittingInfo
# 15
ACTION.USER.3 = USER-ResettingInfo
# 16
ACTION.USER.4 = USER-
# 17
ACTION.USER.5 = USER-
# 18
ACTION.USER.6 = USER-
# 19
ACTION.USER.7 = USER-
# ############################################################
